### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by eggggi** [pcrbot/dasima#1]
建议用list保存各个句子，从0到len(list)之间随机一个数，把随机到的数当成下标从list取出数据再发送。。。
你现在这种写法太可怕了\_(:з」∠)\_

**Comment by eggggi** [comment]
这种写法让我回想起我刚学编程的时候，用一堆printf打印表格\_(:з」∠)\_

**Comment by corvo007** [comment]
> 建议用list保存各个句子，从0到len(list)之间随机一个数，把随机到的数当成下标从list取出数据再发送。。。
> 你现在这种写法太可怕了_(:з」∠)_

可以用list保存，然后用random.choice直接取一条发送。比如：
``` python
sentences = ["第一句话","第二句话",...]
@sv.on_fullmatch(('发病', '大司马'))
async def dsmmylove(bot, ev):
    ....
    await bot.send(random.choice(sentences))

```

**Comment by deepdarkssj** [comment]
这种逆天写法才是精髓啊，只有金轮中毒到需要remake的程度才能写出这样的代码，建议不要改！

**Comment by eggggi** [comment]
> > 建议用list保存各个句子，从0到len(list)之间随机一个数，把随机到的数当成下标从list取出数据再发送。。。
> > 你现在这种写法太可怕了_(:з」∠)_
> 
> 可以用list保存，然后用random.choice直接取一条发送。比如：
> 
> ```python
> sentences = ["第一句话","第二句话",...]
> @sv.on_fullmatch(('发病', '大司马'))
> async def dsmmylove(bot, ev):
>     ....
>     await bot.send(random.choice(sentences))
> ```
